-- 1.A
CREATE TABLE FIGURY (
    ID NUMBER(1) PRIMARY KEY,
    KSZTALT MDSYS.SDO_GEOMETRY
);

-- 1.B
DELETE FROM FIGURY;

INSERT INTO FIGURY VALUES(1,
    MDSYS.SDO_GEOMETRY(2003, NULL, NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,4),
        MDSYS.SDO_ORDINATE_ARRAY(5,3, 7,5, 5,7)
    )
);

INSERT INTO FIGURY VALUES(2,
    MDSYS.SDO_GEOMETRY(2003, NULL, NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),
        MDSYS.SDO_ORDINATE_ARRAY(1,1, 5,5)
    )
);

INSERT INTO FIGURY VALUES(3,
    MDSYS.SDO_GEOMETRY(2006, NULL, NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,4,2, 1,2,1, 5,2,2),
        MDSYS.SDO_ORDINATE_ARRAY(3,2, 6,2, 7,3, 8,2, 7,1)
    )
);

-- 1.C
INSERT INTO FIGURY VALUES(4,
    MDSYS.SDO_GEOMETRY(2003, NULL, NULL,
        MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,4),
        MDSYS.SDO_ORDINATE_ARRAY(5,3, 7,3, 9,3)
    )
);

-- 1.D
SELECT ID, SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(KSZTALT, 0.01) VAL FROM FIGURY;

-- 1.E
DELETE FROM FIGURY WHERE SDO_GEOM.VALIDATE_GEOMETRY(KSZTALT, 0.01) <> 'TRUE';

-- 1.F
COMMIT;
