-- 1.A
CREATE TABLE A6_LRS (GEOM SDO_GEOMETRY);

-- 1.B
INSERT INTO A6_LRS 
SELECT SR.GEOM FROM STREETS_AND_RAILROADS SR, MAJOR_CITIES C
WHERE SDO_RELATE(SR.geom, SDO_GEOM.SDO_BUFFER(C.geom, 10, 1, 'unit=km'), 'MASK=ANYINTERACT') = 'TRUE' 
AND C.CITY_NAME = 'Koszalin';

-- 1.C
SELECT SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km') DISTANCE, 
    ST_LINESTRING(GEOM).ST_NUMPOINTS() ST_NUMPOINTS 
FROM A6_LRS;

-- 1.D
UPDATE A6_LRS SET GEOM = SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, 276.681);

-- 1.E
INSERT INTO USER_SDO_GEOM_METADATA VALUES ('A6_LRS', 'GEOM', 
    MDSYS.SDO_DIM_ARRAY(
        MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1), 
        MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
        MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1)), 
    8307);
                            
-- 1.F
CREATE INDEX A6_LRS_IDX ON A6_LRS(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- 2.A
SELECT SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500 FROM A6_LRS;

-- 2.B
SELECT SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT FROM A6_LRS;

-- 2.C
SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0) KM150 FROM A6_LRS;

-- 2.D
SELECT SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPPED FROM A6_LRS;

-- 2.E
SELECT SDO_LRS.GET_NEXT_SHAPE_PT(A6.GEOM, SDO_LRS.PROJECT_PT(A6.GEOM, C.GEOM)) WJAZD_NA_A6
FROM A6_LRS A6, MAJOR_CITIES C WHERE C.CITY_NAME = 'Slupsk';

-- 2.F.
SELECT SDO_GEOM.SDO_LENGTH(SDO_LRS.OFFSET_GEOM_SEGMENT(A6.GEOM, M.DIMINFO, 50, 200, 50, 'unit=m'), 1, 'unit=km') AS KOSZT
FROM A6_LRS A6, USER_SDO_GEOM_METADATA M 
WHERE M.TABLE_NAME = 'A6_LRS' AND M.COLUMN_NAME = 'GEOM';
